apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Values.namespace.name }}
  labels:
    app: postgres
    {{- include "finsightx.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.postgres.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.postgres.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: {{ .Values.namespace.name }}
  labels:
    app: minio
    {{- include "finsightx.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.minio.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.minio.size }}