apiVersion: v1
kind: Secret
metadata:
  name: finsightx-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "finsightx.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.global.jwt.secretKey | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.global.minio.secretKey | quote }}
  MINIO_ROOT_USER: {{ .Values.global.minio.accessKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.global.postgres.password | quote }}