FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY models ./models

ENV MODEL_PATH=/app/models/fraud_random_forest.joblib
ENV MODEL_VERSION=7D

EXPOSE 8008

CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8008"]