apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: finsightx
spec:
  replicas: 1

  selector:
    matchLabels:
      app: grafana

  template:
    metadata:
      labels:
        app: grafana

    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.5.2
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"

            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"

            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"

          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana

          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: grafana-storage
          emptyDir: {}